data = [
    {
        "Name": "Cristiano Ronaldo",
        "Followers": 337,
        "Description": "Footballer",
        "Country": "Portugal",
    },
    {
        "Name": "Dwayne 'The Rock' Johnson",
        "Followers": 254,
        "Description": "Actor",
        "Country": "United States",
    },
    {
        "Name": "Ariana Grande",
        "Followers": 252,
        "Description": "Singer",
        "Country": "United States",
    },
    {
        "Name": "Selena Gomez",
        "Followers": 246,
        "Description": "Singer",
        "Country": "United States",
    },
    {
        "Name": "Kylie Jenner",
        "Followers": 242,
        "Description": "Businesswoman/TV personality",
        "Country": "United States",
    },
    {
        "Name": "Kim Kardashian",
        "Followers": 237,
        "Description": "Businesswoman/TV personality",
        "Country": "United States",
    },
    {
        "Name": "Lionel Messi",
        "Followers": 223,
        "Description": "Footballer",
        "Country": "Argentina",
    },
    {
        "Name": "Beyoncé",
        "Followers": 202,
        "Description": "Singer",
        "Country": "United States",
    },
    {
        "Name": "Neymar Jr.",
        "Followers": 200,
        "Description": "Footballer",
        "Country": "Brazil",
    },
    {
        "Name": "Taylor Swift",
        "Followers": 179,
        "Description": "Singer",
        "Country": "United States",
    },
    {
        "Name": "Justin Bieber",
        "Followers": 173,
        "Description": "Singer",
        "Country": "Canada",
    },
    {
        "Name": "Kendall Jenner",
        "Followers": 164,
        "Description": "Model/TV personality",
        "Country": "United States",
    },
    {
        "Name": "National Geographic",
        "Followers": 159,
        "Description": "Media brand",
        "Country": "United States",
    },
    {
        "Name": "Jennifer Lopez",
        "Followers": 158,
        "Description": "Singer/Actress",
        "Country": "United States",
    },
    {
        "Name": "Nicki Minaj",
        "Followers": 155,
        "Description": "Rapper",
        "Country": "United States",
    },
    {
        "Name": "Miley Cyrus",
        "Followers": 133,
        "Description": "Singer/Actress",
        "Country": "United States",
    },
    {
        "Name": "Katy Perry",
        "Followers": 132,
        "Description": "Singer",
        "Country": "United States",
    },
    {
        "Name": "Demi Lovato",
        "Followers": 129,
        "Description": "Singer/Actress",
        "Country": "United States",
    },
    {
        "Name": "Rihanna",
        "Followers": 128,
        "Description": "Singer/Fashion designer",
        "Country": "Barbados",
    },
    {
        "Name": "Kourtney Kardashian",
        "Followers": 123,
        "Description": "TV personality",
        "Country": "United States",
    },
    {
        "Name": "Kevin Hart",
        "Followers": 118,
        "Description": "Comedian/Actor",
        "Country": "United States",
    },
    {
        "Name": "Ellen DeGeneres",
        "Followers": 115,
        "Description": "TV host/Comedian",
        "Country": "United States",
    },
    {
        "Name": "Billie Eilish",
        "Followers": 111,
        "Description": "Singer",
        "Country": "United States",
    },
    {
        "Name": "Shakira",
        "Followers": 107,
        "Description": "Singer",
        "Country": "Colombia",
    },
    {
        "Name": "Zendaya",
        "Followers": 106,
        "Description": "Actress/Singer",
        "Country": "United States",
    },
    {
        "Name": "Virat Kohli",
        "Followers": 116,
        "Description": "Cricketer",
        "Country": "India",
    },
    {"Name": "Drake", "Followers": 103, "Description": "Rapper", "Country": "Canada"},
    {
        "Name": "David Beckham",
        "Followers": 102,
        "Description": "Former footballer",
        "Country": "England",
    },
    {
        "Name": "Will Smith",
        "Followers": 101,
        "Description": "Actor",
        "Country": "United States",
    },
    {
        "Name": "Chris Brown",
        "Followers": 99.5,
        "Description": "Singer",
        "Country": "United States",
    },
    {
        "Name": "Gigi Hadid",
        "Followers": 67.9,
        "Description": "Model",
        "Country": "United States",
    },
    {
        "Name": "Emma Watson",
        "Followers": 63.4,
        "Description": "Actress/Activist",
        "Country": "United Kingdom",
    },
    {
        "Name": "Gal Gadot",
        "Followers": 62.8,
        "Description": "Actress",
        "Country": "Israel",
    },
]
